export const TICKER_UNIVERSE = [
  { ticker: "AAPL", sector: "Technology" },
  { ticker: "MSFT", sector: "Technology" },
  { ticker: "NVDA", sector: "Technology" },
  { ticker: "AVGO", sector: "Technology" },
  { ticker: "ORCL", sector: "Technology" },
  { ticker: "CRM", sector: "Technology" },
  { ticker: "ADBE", sector: "Technology" },
  { ticker: "AMD", sector: "Technology" },
  { ticker: "CSCO", sector: "Technology" },
  { ticker: "QCOM", sector: "Technology" },
  { ticker: "INTC", sector: "Technology" },
  { ticker: "TXN", sector: "Technology" },
  { ticker: "MU", sector: "Technology" },
  { ticker: "NOW", sector: "Technology" },
  { ticker: "UBER", sector: "Technology" },
  { ticker: "PLTR", sector: "Technology" },
  { ticker: "SNOW", sector: "Technology" },
  { ticker: "CRWD", sector: "Technology" },
  { ticker: "PANW", sector: "Technology" },
  { ticker: "SHOP", sector: "Technology" },

  { ticker: "GOOGL", sector: "Communication Services" },
  { ticker: "META", sector: "Communication Services" },
  { ticker: "NFLX", sector: "Communication Services" },
  { ticker: "DIS", sector: "Communication Services" },
  { ticker: "TMUS", sector: "Communication Services" },
  { ticker: "T", sector: "Communication Services" },
  { ticker: "VZ", sector: "Communication Services" },
  { ticker: "CHTR", sector: "Communication Services" },
  { ticker: "TTWO", sector: "Communication Services" },
  { ticker: "EA", sector: "Communication Services" },

  { ticker: "AMZN", sector: "Consumer Discretionary" },
  { ticker: "TSLA", sector: "Consumer Discretionary" },
  { ticker: "HD", sector: "Consumer Discretionary" },
  { ticker: "MCD", sector: "Consumer Discretionary" },
  { ticker: "NKE", sector: "Consumer Discretionary" },
  { ticker: "SBUX", sector: "Consumer Discretionary" },
  { ticker: "BKNG", sector: "Consumer Discretionary" },
  { ticker: "LOW", sector: "Consumer Discretionary" },
  { ticker: "TJX", sector: "Consumer Discretionary" },
  { ticker: "CMG", sector: "Consumer Discretionary" },
  { ticker: "MAR", sector: "Consumer Discretionary" },
  { ticker: "RCL", sector: "Consumer Discretionary" },
  { ticker: "ABNB", sector: "Consumer Discretionary" },
  { ticker: "GM", sector: "Consumer Discretionary" },
  { ticker: "F", sector: "Consumer Discretionary" },

  { ticker: "WMT", sector: "Consumer Staples" },
  { ticker: "COST", sector: "Consumer Staples" },
  { ticker: "PG", sector: "Consumer Staples" },
  { ticker: "KO", sector: "Consumer Staples" },
  { ticker: "PEP", sector: "Consumer Staples" },
  { ticker: "PM", sector: "Consumer Staples" },
  { ticker: "MO", sector: "Consumer Staples" },
  { ticker: "MDLZ", sector: "Consumer Staples" },
  { ticker: "CL", sector: "Consumer Staples" },
  { ticker: "TGT", sector: "Consumer Staples" },

  { ticker: "JPM", sector: "Financials" },
  { ticker: "V", sector: "Financials" },
  { ticker: "MA", sector: "Financials" },
  { ticker: "BRK-B", sector: "Financials" },
  { ticker: "BAC", sector: "Financials" },
  { ticker: "WFC", sector: "Financials" },
  { ticker: "GS", sector: "Financials" },
  { ticker: "MS", sector: "Financials" },
  { ticker: "BLK", sector: "Financials" },
  { ticker: "AXP", sector: "Financials" },
  { ticker: "SCHW", sector: "Financials" },
  { ticker: "C", sector: "Financials" },
  { ticker: "BX", sector: "Financials" },
  { ticker: "KKR", sector: "Financials" },
  { ticker: "COF", sector: "Financials" },

  { ticker: "LLY", sector: "Healthcare" },
  { ticker: "UNH", sector: "Healthcare" },
  { ticker: "JNJ", sector: "Healthcare" },
  { ticker: "MRK", sector: "Healthcare" },
  { ticker: "ABBV", sector: "Healthcare" },
  { ticker: "PFE", sector: "Healthcare" },
  { ticker: "ABT", sector: "Healthcare" },
  { ticker: "TMO", sector: "Healthcare" },
  { ticker: "ISRG", sector: "Healthcare" },
  { ticker: "DHR", sector: "Healthcare" },
  { ticker: "AMGN", sector: "Healthcare" },
  { ticker: "GILD", sector: "Healthcare" },
  { ticker: "BMY", sector: "Healthcare" },
  { ticker: "CVS", sector: "Healthcare" },
  { ticker: "VRTX", sector: "Healthcare" },

  { ticker: "GE", sector: "Industrials" },
  { ticker: "CAT", sector: "Industrials" },
  { ticker: "RTX", sector: "Industrials" },
  { ticker: "BA", sector: "Industrials" },
  { ticker: "UNP", sector: "Industrials" },
  { ticker: "LMT", sector: "Industrials" },
  { ticker: "DE", sector: "Industrials" },
  { ticker: "UPS", sector: "Industrials" },
  { ticker: "HON", sector: "Industrials" },
  { ticker: "NOC", sector: "Industrials" },
  { ticker: "ETN", sector: "Industrials" },
  { ticker: "PH", sector: "Industrials" },
  { ticker: "MMM", sector: "Industrials" },
  { ticker: "FDX", sector: "Industrials" },
  { ticker: "GD", sector: "Industrials" },

  { ticker: "XOM", sector: "Energy" },
  { ticker: "CVX", sector: "Energy" },
  { ticker: "COP", sector: "Energy" },
  { ticker: "SLB", sector: "Energy" },
  { ticker: "EOG", sector: "Energy" },
  { ticker: "MPC", sector: "Energy" },
  { ticker: "PSX", sector: "Energy" },
  { ticker: "VLO", sector: "Energy" },
  { ticker: "OXY", sector: "Energy" },
  { ticker: "HAL", sector: "Energy" },

  { ticker: "NEE", sector: "Utilities" },
  { ticker: "DUK", sector: "Utilities" },
  { ticker: "SO", sector: "Utilities" },
  { ticker: "D", sector: "Utilities" },
  { ticker: "AEP", sector: "Utilities" },
  { ticker: "SRE", sector: "Utilities" },
  { ticker: "EXC", sector: "Utilities" },
  { ticker: "XEL", sector: "Utilities" },

  { ticker: "LIN", sector: "Materials" },
  { ticker: "APD", sector: "Materials" },
  { ticker: "SHW", sector: "Materials" },
  { ticker: "FCX", sector: "Materials" },
  { ticker: "NEM", sector: "Materials" },
  { ticker: "DD", sector: "Materials" },
  { ticker: "DOW", sector: "Materials" },
  { ticker: "ECL", sector: "Materials" },

  { ticker: "AMT", sector: "Real Estate" },
  { ticker: "PLD", sector: "Real Estate" },
  { ticker: "CCI", sector: "Real Estate" },
  { ticker: "EQIX", sector: "Real Estate" },
  { ticker: "SPG", sector: "Real Estate" },
  { ticker: "O", sector: "Real Estate" },
  { ticker: "PSA", sector: "Real Estate" },
  { ticker: "WELL", sector: "Real Estate" },
] as const;