"""
seed_tickers.py — generates scripts/tickers_seed.sql for Supabase

Usage:
    pip install yfinance requests
    python scripts/seed_tickers.py

Then paste scripts/tickers_seed.sql into Supabase -> SQL Editor and run.
"""

import csv
import io
import time
import sys
import subprocess

# ── deps ──────────────────────────────────────────────────────────────────────
try:
    import yfinance as yf
    import requests
except ImportError:
    print("Installing required packages...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "yfinance", "requests"])
    import yfinance as yf
    import requests

# ── fetch S&P 500 from CSV ────────────────────────────────────────────────────

CSV_URL = "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv"

def get_sp500() -> list[dict]:
    """Returns list of {symbol, name, sector} from the CSV."""
    print("Fetching S&P 500 list from GitHub...")
    resp = requests.get(CSV_URL, timeout=15)
    resp.raise_for_status()
    reader = csv.DictReader(io.StringIO(resp.text))
    rows = []
    for row in reader:
        symbol = row.get("Symbol", "").strip().replace(".", "-")
        name   = row.get("Name", "").strip()
        sector = row.get("Sector", "").strip()
        if symbol:
            rows.append({"symbol": symbol, "name": name, "sector": sector})
    print(f"  -> {len(rows)} S&P 500 tickers loaded")
    return rows

# ── extras ────────────────────────────────────────────────────────────────────

EXTRA_TICKERS = [
    "PLTR", "RIVN", "SOFI", "GME", "AMC", "COIN", "HOOD", "RBLX", "SNAP",
    "UBER", "LYFT", "ABNB", "DASH", "ARM", "SMCI", "MSTR", "DKNG", "PENN",
    "SOUN", "IONQ", "RGTI", "QUBT", "ACHR", "JOBY", "LUNR", "RKLB",
]

# ── yfinance market cap fetch ─────────────────────────────────────────────────

def fetch_market_cap(symbol: str) -> int:
    """Returns market cap from yfinance, or 0 on failure."""
    try:
        info = yf.Ticker(symbol).info
        return int(info.get("marketCap") or 0)
    except Exception:
        return 0

# ── SQL helpers ───────────────────────────────────────────────────────────────

def escape(s: str) -> str:
    return s.replace("'", "''")

def to_insert(row: dict) -> str:
    return (
        f"INSERT INTO tickers (symbol, name, sector, market_cap) VALUES ("
        f"'{escape(row['symbol'])}', "
        f"'{escape(row['name'])}', "
        f"'{escape(row['sector'])}', "
        f"{row['market_cap']}"
        f");"
    )

# ── main ──────────────────────────────────────────────────────────────────────

def main():
    # Build master list: S&P 500 from CSV + extras
    sp500 = get_sp500()
    sp500_symbols = {r["symbol"] for r in sp500}

    # Turn extras into stub rows (name/sector filled by yfinance fallback)
    extra_rows = [
        {"symbol": s, "name": s, "sector": ""}
        for s in EXTRA_TICKERS
        if s not in sp500_symbols
    ]

    all_rows = sp500 + extra_rows
    total = len(all_rows)
    print(f"\nTotal tickers to process: {total}\n")

    results: list[dict] = []
    failed = 0

    for i, base in enumerate(all_rows, 1):
        symbol = base["symbol"]
        market_cap = fetch_market_cap(symbol)

        # For extras, try to get a proper name/sector from yfinance
        name   = base["name"]
        sector = base["sector"]
        if not name or not sector:
            try:
                info   = yf.Ticker(symbol).info
                name   = info.get("longName") or info.get("shortName") or symbol
                sector = info.get("sector") or "Other"
                # avoid double-fetch delay — market_cap already fetched above for sp500
                # but for extras the info call above replaces the stub values
            except Exception:
                name   = name or symbol
                sector = sector or "Other"
        else:
            # yfinance already called above for market_cap; no extra call needed
            pass

        if not sector:
            sector = "Other"
        if not name:
            name = symbol

        results.append({
            "symbol":     symbol,
            "name":       name,
            "sector":     sector,
            "market_cap": market_cap,
        })

        if i % 50 == 0 or i == total:
            print(f"  [{i:>3}/{total}]  ok {len(results)} rows  (latest: {symbol})")

        time.sleep(0.5)

    # ── write SQL ─────────────────────────────────────────────────────────────
    out_path = "scripts/tickers_seed.sql"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- Generated by scripts/seed_tickers.py\n")
        f.write(f"-- {len(results)} tickers  (S&P 500 + popular extras)\n\n")
        f.write("DELETE FROM tickers;\n\n")
        for row in results:
            f.write(to_insert(row) + "\n")

    print(f"\nDone!  Done!")
    print(f"    Tickers written: {len(results)}")
    print(f"    SQL file:        {out_path}")
    print(f"\nNext: paste {out_path} into Supabase -> SQL Editor and run it.")

if __name__ == "__main__":
    main()
